### ISSUE TITLE
Google Maps disregarding display:none; CSS property in iPads.

### ISSUE THREAD

**Issue by antonymuga** [antonymuga/antonymuga.github.io#4]
When the index page is viewed on an iPad, an overflow of the Google Maps still appears.

**Comment by edwardvercoe** [comment]
Do you have a media query in your CSS file addressing what to display when the viewport is the size of an iPad?
A good start would be to perhaps review your media queries to see if they match your intended result! :)

**Comment by antonymuga** [comment]
I've played around with the media queries style-sheet values for screen size but the issue still persists.Thanks for you feedback anyway.
